name: Check all tests

on:
  pull_request

jobs:
  check-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o projeto...
        uses: actions/checkout@2

      - name: Instalando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Instalar, build e rodar os testes
        run: |
          npm install
          npm build
          npm test